# 問題の概要
与えられた数列の中から順に最大値を取るAとBのそれぞれの合計の差を求める問題。

In [32]:
import numpy as np

N = int(input())
a_list = np.array(list(map(int,input().split())))


毎回AとBはそれぞれ最大値を取る。  
方法１：毎回最大値を取ることをfor文やwhileで繰り返す。  
方法２：ソートした後、後ろから前にかけて、一個飛ばしで足していったものをAの和、残ったものの総和をBの和として差を求める。

In [39]:
a_list

array([2, 3, 4, 6])

In [ ]:
a_list.sort()

In [40]:
a_list

array([2, 3, 4, 6])

In [49]:
# 要素数が偶数か奇数かでAがカードを取得する回数を変える
if N%2==0:
    A = a_list[1:N:2]
    B = a_list[:N:2]
else:
    A = a_list[:N:2]
    B = a_list[1:N:2]

In [45]:
A

array([3, 6])

In [50]:
B

array([2, 4])

In [51]:
A_sum = A.sum()
B_sum = B.sum()

In [48]:
A_sum

np.int64(9)

In [52]:
B_sum

np.int64(6)

In [54]:
int(A_sum-B_sum)

3

# 自分の解答

In [ ]:
import numpy as np

N = int(input())
a_list = np.array(list(map(int,input().split())))

#ソートすることで取得順とindexを連携させる
a_list.sort()

# 要素数が偶数か奇数かでAがカードを取得する回数を変える
if N%2==0:
    A = a_list[1:N:2]
    B = a_list[:N:2]
else:
    A = a_list[:N:2]
    B = a_list[1:N:2]

print(int(A.sum()-B.sum()))